//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveSubscriptions
    {
        public System.Guid ActiveID { get; set; }
        public System.Guid SubscriptionID { get; set; }
        public Nullable<int> TotalNotifications { get; set; }
        public int TotalSuccesses { get; set; }
        public int TotalFailures { get; set; }
    
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
