//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public System.Guid BatchID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string Action { get; set; }
        public string Item { get; set; }
        public string Parent { get; set; }
        public string Param { get; set; }
        public Nullable<bool> BoolParam { get; set; }
        public byte[] Content { get; set; }
        public string Properties { get; set; }
    }
}
