//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CachePolicy
    {
        public System.Guid CachePolicyID { get; set; }
        public System.Guid ReportID { get; set; }
        public int ExpirationFlags { get; set; }
        public Nullable<int> CacheExpiration { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
