//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChunkSegmentMapping
    {
        public System.Guid ChunkId { get; set; }
        public System.Guid SegmentId { get; set; }
        public long StartByte { get; set; }
        public int LogicalByteCount { get; set; }
        public int ActualByteCount { get; set; }
    }
}
