//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSource
    {
        public System.Guid DSID { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public Nullable<System.Guid> SubscriptionID { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public Nullable<System.Guid> Link { get; set; }
        public Nullable<int> CredentialRetrieval { get; set; }
        public string Prompt { get; set; }
        public byte[] ConnectionString { get; set; }
        public byte[] OriginalConnectionString { get; set; }
        public Nullable<bool> OriginalConnectStringExpressionBased { get; set; }
        public byte[] UserName { get; set; }
        public byte[] Password { get; set; }
        public Nullable<int> Flags { get; set; }
        public int Version { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
