//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public System.Guid EventID { get; set; }
        public string EventType { get; set; }
        public string EventData { get; set; }
        public System.DateTime TimeEntered { get; set; }
        public Nullable<System.DateTime> ProcessStart { get; set; }
        public Nullable<System.DateTime> ProcessHeartbeat { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
    }
}
