//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public System.Guid HistoryID { get; set; }
        public System.Guid ReportID { get; set; }
        public System.Guid SnapshotDataID { get; set; }
        public System.DateTime SnapshotDate { get; set; }
    }
}
