//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelDrill
    {
        public System.Guid ModelDrillID { get; set; }
        public System.Guid ModelID { get; set; }
        public System.Guid ReportID { get; set; }
        public string ModelItemID { get; set; }
        public byte Type { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Catalog Catalog1 { get; set; }
    }
}
