//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelPerspective
    {
        public System.Guid ID { get; set; }
        public System.Guid ModelID { get; set; }
        public string PerspectiveID { get; set; }
        public string PerspectiveName { get; set; }
        public string PerspectiveDescription { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
