//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public System.Guid NotificationID { get; set; }
        public System.Guid SubscriptionID { get; set; }
        public Nullable<System.Guid> ActivationID { get; set; }
        public System.Guid ReportID { get; set; }
        public Nullable<System.DateTime> SnapShotDate { get; set; }
        public string ExtensionSettings { get; set; }
        public string Locale { get; set; }
        public string Parameters { get; set; }
        public Nullable<System.DateTime> ProcessStart { get; set; }
        public System.DateTime NotificationEntered { get; set; }
        public Nullable<System.DateTime> ProcessAfter { get; set; }
        public Nullable<int> Attempt { get; set; }
        public System.DateTime SubscriptionLastRunTime { get; set; }
        public string DeliveryExtension { get; set; }
        public System.Guid SubscriptionOwnerID { get; set; }
        public bool IsDataDriven { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
        public Nullable<System.DateTime> ProcessHeartbeat { get; set; }
        public int Version { get; set; }
        public int ReportZone { get; set; }
    
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
