//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public Policies()
        {
            this.Catalog = new HashSet<Catalog>();
            this.ModelItemPolicy = new HashSet<ModelItemPolicy>();
            this.PolicyUserRole = new HashSet<PolicyUserRole>();
            this.SecData = new HashSet<SecData>();
        }
    
        public System.Guid PolicyID { get; set; }
        public Nullable<byte> PolicyFlag { get; set; }
    
        public virtual ICollection<Catalog> Catalog { get; set; }
        public virtual ICollection<ModelItemPolicy> ModelItemPolicy { get; set; }
        public virtual ICollection<PolicyUserRole> PolicyUserRole { get; set; }
        public virtual ICollection<SecData> SecData { get; set; }
    }
}
