//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSchedule
    {
        public System.Guid ScheduleID { get; set; }
        public System.Guid ReportID { get; set; }
        public Nullable<System.Guid> SubscriptionID { get; set; }
        public int ReportAction { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
