//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.PolicyUserRole = new HashSet<PolicyUserRole>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public string TaskMask { get; set; }
        public byte RoleFlags { get; set; }
    
        public virtual ICollection<PolicyUserRole> PolicyUserRole { get; set; }
    }
}
