//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningJobs
    {
        public string JobID { get; set; }
        public System.DateTime StartDate { get; set; }
        public string ComputerName { get; set; }
        public string RequestName { get; set; }
        public string RequestPath { get; set; }
        public System.Guid UserId { get; set; }
        public string Description { get; set; }
        public int Timeout { get; set; }
        public short JobAction { get; set; }
        public short JobType { get; set; }
        public short JobStatus { get; set; }
    }
}
