//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.ReportSchedule = new HashSet<ReportSchedule>();
        }
    
        public System.Guid ScheduleID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Flags { get; set; }
        public Nullable<System.DateTime> NextRunTime { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RecurrenceType { get; set; }
        public Nullable<int> MinutesInterval { get; set; }
        public Nullable<int> DaysInterval { get; set; }
        public Nullable<int> WeeksInterval { get; set; }
        public Nullable<int> DaysOfWeek { get; set; }
        public Nullable<int> DaysOfMonth { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> MonthlyWeek { get; set; }
        public Nullable<int> State { get; set; }
        public string LastRunStatus { get; set; }
        public Nullable<int> ScheduledRunTimeout { get; set; }
        public System.Guid CreatedById { get; set; }
        public string EventType { get; set; }
        public string EventData { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> ConsistancyCheck { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<ReportSchedule> ReportSchedule { get; set; }
        public virtual Users Users { get; set; }
    }
}
