//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecData
    {
        public System.Guid SecDataID { get; set; }
        public System.Guid PolicyID { get; set; }
        public int AuthType { get; set; }
        public string XmlDescription { get; set; }
        public byte[] NtSecDescPrimary { get; set; }
        public string NtSecDescSecondary { get; set; }
    
        public virtual Policies Policies { get; set; }
    }
}
