//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentedChunk
    {
        public System.Guid ChunkId { get; set; }
        public System.Guid SnapshotDataId { get; set; }
        public byte ChunkFlags { get; set; }
        public string ChunkName { get; set; }
        public int ChunkType { get; set; }
        public short Version { get; set; }
        public string MimeType { get; set; }
        public long SegmentedChunkId { get; set; }
    }
}
