//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerParametersInstance
    {
        public string ServerParametersID { get; set; }
        public string ParentID { get; set; }
        public string Path { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Timeout { get; set; }
        public System.DateTime Expiration { get; set; }
        public byte[] ParametersValues { get; set; }
    }
}
