//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerUpgradeHistory
    {
        public long UpgradeID { get; set; }
        public string ServerVersion { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
