//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnapshotData
    {
        public System.Guid SnapshotDataID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ParamsHash { get; set; }
        public string QueryParams { get; set; }
        public string EffectiveParams { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DependsOnUser { get; set; }
        public int PermanentRefcount { get; set; }
        public int TransientRefcount { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<bool> HasDocMap { get; set; }
        public Nullable<short> PaginationMode { get; set; }
        public Nullable<int> ProcessingFlags { get; set; }
    }
}
