//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public Subscriptions()
        {
            this.ActiveSubscriptions = new HashSet<ActiveSubscriptions>();
            this.Notifications = new HashSet<Notifications>();
            this.ReportSchedule = new HashSet<ReportSchedule>();
        }
    
        public System.Guid SubscriptionID { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.Guid Report_OID { get; set; }
        public string Locale { get; set; }
        public int InactiveFlags { get; set; }
        public string ExtensionSettings { get; set; }
        public System.Guid ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Description { get; set; }
        public string LastStatus { get; set; }
        public string EventType { get; set; }
        public string MatchData { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public string Parameters { get; set; }
        public string DataSettings { get; set; }
        public string DeliveryExtension { get; set; }
        public int Version { get; set; }
        public int ReportZone { get; set; }
    
        public virtual ICollection<ActiveSubscriptions> ActiveSubscriptions { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<ReportSchedule> ReportSchedule { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
