//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Catalog = new HashSet<Catalog>();
            this.Catalog1 = new HashSet<Catalog>();
            this.PolicyUserRole = new HashSet<PolicyUserRole>();
            this.Schedule = new HashSet<Schedule>();
            this.Subscriptions = new HashSet<Subscriptions>();
            this.Subscriptions1 = new HashSet<Subscriptions>();
        }
    
        public System.Guid UserID { get; set; }
        public byte[] Sid { get; set; }
        public int UserType { get; set; }
        public int AuthType { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Catalog> Catalog { get; set; }
        public virtual ICollection<Catalog> Catalog1 { get; set; }
        public virtual ICollection<PolicyUserRole> PolicyUserRole { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<Subscriptions> Subscriptions { get; set; }
        public virtual ICollection<Subscriptions> Subscriptions1 { get; set; }
    }
}
